const UI_PASSCODE='3699';
const state={data:null,unlocked:false};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?esc(v):'—';
const pct=v=>v===null||v===undefined?'—':`${Number(v).toFixed(1)}%`;
const money=v=>{if(v===null||v===undefined||!Number.isFinite(Number(v)))return'—';const n=Number(v),unit=Math.abs(n)>=100000000?'億':'萬',value=unit==='億'?n/100000000:n/10000;return `${value.toLocaleString('zh-TW',{minimumFractionDigits:1,maximumFractionDigits:1})} ${unit}`};
const tone=v=>Number(v)>0?'gain':Number(v)<0?'loss':'';
const flowTone=v=>{const n=Number(v);if(!Number.isFinite(n)||n===0)return'';const level=Math.abs(n)>=50000000?'strong':Math.abs(n)>=10000000?'medium':'light';return `${n>0?'buy':'sell'}-${level}`};
const status=v=>v==='SETTLED'?'已出場':v==='OPEN'?'持有中':v||'—';
const stage=v=>({BUILDING:'建倉中',ACCUMULATING:'建倉／加碼中',ADDING:'加碼中',HOLDING:'持有中',LOCKED:'持有觀察',EXITING:'出場中',SETTLED:'已結算'})[v]||v||'—';
const recency=v=>{if(!v)return'event-stale';const now=state.data?.price_data_through||state.data?.generated_on;const days=Math.floor((Date.parse(now)-Date.parse(v))/86400000);return days<=2?'event-fresh':days<=7?'event-current':days<=21?'event-recent':'event-stale'};
function metrics(x){return `<div class="metrics"><span>5日淨額 <b class="${flowTone(x.net_amount_5d)}">${money(x.net_amount_5d)}</b></span><span>20日淨額 <b class="${flowTone(x.net_amount_20d)}">${money(x.net_amount_20d)}</b></span><span>報酬 <b class="${tone(x.current_return_pct)}">${pct(x.current_return_pct)}</b></span><span>參與據點 <b>${x.participant_count??'—'}</b></span></div>`}
function dates(x){const reducing=Number(x.net_amount_5d)<0;return `<div class="date-strip"><span class="entry-date">首筆建倉 <b>${date(x.first_buy_date)}</b></span><span class="entry-date">錨點建倉 <b>${date(x.anchor_first_buy_date)}</b></span><span class="entry-date entry-add ${recency(x.latest_buy_date)}">最近加碼 <b>${date(x.latest_buy_date)}</b></span><span class="${reducing?'exit-date reduction-date':''} ${recency(x.last_activity_date)}">${reducing?'最近減碼':'最後活動'} <b>${date(x.last_activity_date)}</b></span><span>庫存高點 <b>${date(x.maximum_inventory_date)}</b></span><span class="exit-date">出場／結算 <b>${date(x.settlement_date)}</b></span></div>`}
function watchCard(x,detail=false){return `<article class="card holding-card"><div class="card-head"><div><p class="eyebrow">${esc(x.symbol||x.stock_code||'—')}</p><h3>${esc(x.stock_name||x.company_name||x.name||'未命名標的')}</h3></div><span class="pill">${esc(stage(x.operation_stage))}</span></div><p class="muted">${esc(x.anchor_group_name||x.group_name||'主力群觀察')}</p>${metrics(x)}${dates(x)}${detail&&x.branches?.length?`<p class="branches">據點：${x.branches.map(esc).join('、')}</p>`:''}</article>`}
function groupCard(g){return `<a class="card group-card" href="#/groups/${encodeURIComponent(g.group_id)}"><div class="card-head"><div><p class="eyebrow">主力群</p><h3>${esc(g.group_name)}</h3></div><span class="pill">信心 ${pct(g.confidence_score)}</span></div><div class="metrics"><span>持股 <b>${g.holdings?.length??0}</b></span><span>近勝率 <b>${pct(g.recent_win_rate_pct)}</b></span><span>加碼檔 <b>${g.recent_add_count??0}</b></span><span>新建倉 <b>${g.new_position_count??0}</b></span></div><p class="muted">${esc(g.summary||'查看成員、持股日期與活動紀錄')}</p></a>`}
function home(){const d=state.data; const watch=d.watchlist||[];const alerts=d.exit_alerts||[];const groups=d.main_force_groups||[];return `<main class="shell"><section class="hero"><p class="eyebrow">M100 Emerging Broker Hunter</p><h1>主力群追蹤儀表板</h1><p>資料日：<b>${date(d.generated_at?.slice?.(0,10)||d.as_of)}</b>　交易／價格資料：<b>${date(d.transaction_data_through)}</b>／<b>${date(d.price_data_through)}</b></p></section><section class="summary"><div><span>追蹤標的</span><b>${watch.length}</b></div><div><span>主力群</span><b>${groups.length}</b></div><div><span>持有中</span><b>${(d.open_positions||[]).length}</b></div><div><span>風險提醒</span><b>${alerts.length}</b></div></section><section><div class="section-title"><h2>今日觀察與建倉進度</h2><p>每檔直接列出建倉、加碼與出場日期。</p></div><div class="cards wide-cards">${watch.length?watch.map(x=>watchCard(x,true)).join(''):'<p class="empty">目前沒有符合條件的觀察標的。</p>'}</div></section><section><div class="section-title"><h2>風險／出場提醒</h2><p>已結算日期會標示在出場／結算欄位。</p></div><div class="cards">${alerts.length?alerts.map(x=>watchCard(x,true)).join(''):'<p class="empty">目前沒有出場提醒。</p>'}</div></section><section><div class="section-title"><h2>主力群</h2><a href="#/groups">查看全部 →</a></div><div class="cards">${groups.slice(0,6).map(groupCard).join('')}</div></section></main>`}
function groups(){const gs=state.data.main_force_groups||[];return `<main class="shell"><section class="hero compact"><p class="eyebrow">主力群檔案</p><h1>群體與持股活動</h1><p>點進任一群組，即可檢視成員、持股、建倉／加碼／出場日期。</p></section><div class="cards">${gs.map(groupCard).join('')}</div></main>`}
function groupDetail(id){const g=(state.data.main_force_groups||[]).find(x=>String(x.group_id)===decodeURIComponent(id));if(!g)return `<main class="shell"><p class="empty">找不到此主力群。</p></main>`;const holds=g.holdings||[];const campaigns=g.campaigns||[];return `<main class="shell"><p class="breadcrumb"><a href="#/groups">← 主力群</a></p><section class="hero compact"><p class="eyebrow">${esc(g.group_id||'主力群')}</p><h1>${esc(g.group_name)}</h1><p>${esc(g.summary||'群組活動與持股明細')}</p><div class="metrics"><span>信心 <b>${pct(g.confidence_score)}</b></span><span>近期勝率 <b>${pct(g.recent_win_rate_pct)}</b></span><span>中位報酬 <b class="${tone(g.median_holding_return_pct)}">${pct(g.median_holding_return_pct)}</b></span><span>最大回撤 <b>${pct(g.max_drawdown_pct)}</b></span></div></section><section><div class="section-title"><h2>群組成員</h2></div><p class="branches">${g.members?.length?g.members.map(x=>esc(x.broker_name||x.name||x)).join('、'):'—'}</p></section><section><div class="section-title"><h2>目前與歷史持股</h2><p>建倉、加碼、庫存峰值和出場日均由快照提供。</p></div><div class="cards wide-cards">${holds.length?holds.map(x=>watchCard(x,true)).join(''):'<p class="empty">尚無持股明細。</p>'}</div></section><section><div class="section-title"><h2>活動紀錄</h2></div><div class="cards">${campaigns.length?campaigns.map(c=>`<article class="card"><p class="eyebrow">${esc(c.symbol||c.stock_code||'—')}</p><h3>${esc(c.stock_name||c.company_name||c.name||'未命名標的')}</h3><p class="stage-line">${esc(stage(c.operation_stage))}　${date(c.first_buy_date)} → ${date(c.settlement_date||c.last_activity_date)}</p>${dates(c)}</article>`).join(''):'<p class="empty">尚無活動紀錄。</p>'}</div></section></main>`}
function methodology(){return `<main class="shell"><section class="hero compact"><p class="eyebrow">資料欄位說明</p><h1>如何看建倉、加碼與出場</h1><p>靜態網站只展示經整理的公開快照，不包含原始券商交易或策略參數。</p></section><section class="card prose"><h2>日期欄位</h2><p><b>首筆建倉</b>是群組對該標的首次出現有效累積的位置；<b>錨點建倉</b>是作為追蹤基準的首筆日期；<b>最近加碼</b>顯示最近一次符合條件的累積；<b>最後活動</b>是最新交易活動日；<b>庫存高點</b>是追蹤期內庫存量最高的日期；<b>出場／結算</b>只在部位已結束且可確認時顯示。</p><p>日期為「—」代表尚未形成可判定事件，或部位仍在進行中，並非網站漏資料。</p></section></main>`}
function render(){const gate=$('#gate'),app=$('#app');if(!state.unlocked){app.hidden=true;gate.hidden=false;return}gate.hidden=true;app.hidden=false;const h=location.hash.replace(/^#\/?/,'');let view=h==='groups'?groups():h.startsWith('groups/')?groupDetail(h.slice(7)):h==='methodology'?methodology():home();app.innerHTML=`<header><a class="brand" href="#/">M100 <span>Emerging Broker Hunter</span></a><nav><a href="#/">首頁</a><a href="#/groups">主力群</a><a href="#/methodology">方法</a><button id="lock">鎖定</button></nav></header>${view}<footer>資料僅供研究與資訊整理使用，非投資建議。</footer>`;$('#lock').onclick=()=>{state.unlocked=false;try{sessionStorage.removeItem('m100-access')}catch{}render()}}
async function init(){try{state.data=await fetch('./data/broker-wave-summary.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('資料載入失敗');return r.json()});try{state.unlocked=sessionStorage.getItem('m100-access')==='1'}catch{}$('#gate-form').onsubmit=e=>{e.preventDefault();if($('#passcode').value.trim()===UI_PASSCODE){state.unlocked=true;try{sessionStorage.setItem('m100-access','1')}catch{}render()}else $('#gate-error').hidden=false};window.addEventListener('hashchange',render);render()}catch(e){$('#gate').hidden=true;$('#app').hidden=false;$('#app').innerHTML=`<main class="shell"><p class="empty">無法載入資料快照，請稍後再試。</p></main>`}}
init();
